data:
  file: "dataset_v2.csv"
  version: "v2"
preprocess:
  target: "MedHouseVal"
  features:
    numerical:
      - "MedInc"
      - "HouseAge" 
      - "AveRooms"
      - "AveBedrms"
      - "Population"
      - "AveOccup"
      - "Latitude"
      - "Longitude"
train:
  target: "MedHouseVal"
  test_size: 0.2
  models:
    - "LinearRegression"
    - "RandomForest"
    - "GradientBoosting"
  hyperparams:
    RandomForest:
      n_estimators: 100
      max_depth: 10
      random_state: 42
    GradientBoosting:
      n_estimators: 100
      learning_rate: 0.1
      random_state: 42
evaluate:
  target: "MedHouseVal"
  metrics:
    - "mse"
    - "r2"
    - "mae"